[es_json]
type = "ESJsonEncoder"
index = "{{ values.index }}"

{% if values.es_index_from_timestamp == True %}
es_index_from_timestamp = true
{%- else -%}
es_index_from_timestamp = false
{%- endif -%}

