[es_payload]
type = "SandboxEncoder"
filename = "lua_encoders/es_payload.lua"

    [es_payload.config]
    es_index_from_timestamp = true
    index = "{% raw %}%{Logger}-%{%Y.%m.%d}{% endraw %}"
    type_name = "{% raw %}%{Type}-%{Hostname}{% endraw %}"
