[gse_{{ alarm_cluster_name }}_filter]
type = "SandboxFilter"
filename = "/usr/share/lma_collector/filters/gse_cluster_filter.lua"
preserve_data = {{ alarm_cluster.preserve_data|default(False)|lower }}
message_matcher = "(Type == 'heka.sandbox.afd_metric' || Type == 'heka.sandbox.gse_metric') && ({{ salt['heka_alarming.alarm_cluster_message_matcher'](alarm_cluster) }})"
module_directory = "/usr/share/lma_collector/common;/usr/share/heka/lua_modules"
ticker_interval = 1

[gse_{{ alarm_cluster_name }}_filter.config]
topology_file = "gse_{{ alarm_cluster_name|replace('-', '_') }}_topology"
activate_alerting = {{ alarm_cluster.alerting|default(True)|lower }}
{%- if alarm_cluster.interval is defined %}
interval = {{ alarm_cluster.interval }}
{%- endif %}
{%- if alarm_cluster.max_inject is defined %}
max_inject = {{ alarm_cluster.max_inject }}
{%- endif %}
{%- if alarm_cluster.warm_up_period is defined %}
warm_up_period = {{ alarm_cluster.warm_up_period }}
{%- endif %}
