[{{ encoder_name }}_encoder]
type = "SandboxEncoder"
filename = "{{ encoder.module_file }}"
{%- if encoder.module_dir is defined %}
module_directory = "{{ encoder.module_dir }}"
{%- endif %}

{%- if encoder.config is mapping %}
[{{ encoder_name }}_encoder.config]
{%- for config_param, config_value in encoder.config.iteritems() %}
{{ config_param }} = {% if config_value is string %}"{{ config_value }}"{% elif config_value in [True, False] %}{{ config_value|lower }}{% else %}{{ config_value }}{% endif %}
{%- endfor %}
{%- endif %}
