[input_{{ name }}]
type = "AMQPInput"
url = "amqp://{{ values.user }}:{{ values.password }}@{{ values.host }}:{{ values.port }}/{{ values.vhost }}"
exchange = "{{ values.exchange }}"
exchange_type = "{{ values.exchange_type }}"
exchange_durability = "{{ values.exchange_durability }}"
exchange_auto_delete = "{{ values.exchange_auto_delete }}"
queue_auto_delete = {{ values.queue_auto_delete }}
queue = "{{ values.queue }}"
routing_key = "{{ values.routing_key }}"
decoder = "{{ values.decoder }}"
splitter = "{{ values.splitter }}"

