[logstreamer_{{ name }}]
type = "LogstreamerInput"
log_directory = "{{ values['log_directory'] }}"
file_match = '{{ values['file_match'] }}'
differentiator = {{ values['differentiator'] }}
decoder = "{{ values['decoder'] }}_decoder"
splitter = "{{ values['splitter'] }}"

