[logstreamer_{{ name }}]
type = "LogstreamerInput"
log_directory = "{{ values['log_directory'] }}"
file_match = '{{ values['file_match'] }}'
{% if values['differentiator'] -%}
differentiator = {{ values['differentiator'] }}
{% endif -%}
decoder = "{#% decoder %#}_decoder"
splitter = "{{ values['splitter'] }}"

