[logstreamer_{{ name }}]
type = "LogstreamerInput"
log_directory = "{{ values.log_directory }}"
file_match = '{{ values.file_match }}'

decoder = "{{ values.decoder }}_decoder"

{% if values.splitter is defined %}
splitter = {{ values.splitter }}
{% endif %}

