[logstreamer_{{ name }}]
type = "LogstreamerInput"
log_directory = "{{ values.log_directory }}"
file_match = '{{ values.file_match }}'
priority = {{ values.priority }}

decoder = "{{ values.decoder }}"

{% if values.splitter is defined %}
splitter = {{ values.splitter }}
{% endif %}

