[OpenStackDecoder]
type = "MultiDecoder"
subs = [ 'OpenStack','OpenStackTrace' ]
#cascade_strategy = "all"
cascade_strategy = "first-wins"
log_sub_errors = false

[OpenStack]
type = "PayloadRegexDecoder"
match_regex = '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}.\d{3})\s(?P<pid>\d+)\s(?P<severity>\w+)\s(?P<programname>\D+)\s\[(?P<id>.+)\]\s(?P<payload>.*)'
timestamp_layout = "2015-10-06 11:34:37.243"

[OpenStackTrace]
type = "PayloadRegexDecoder"
match_regex = '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2}.\d{3})\s(?P<pid>\d+)\s(?P<severity>TRACE)\s(?P<programname>.\S+)\s(?P<Payload>.*)'
timestamp_layout = "2015-10-06 11:34:37.243"

[OpenStack.message_fields]
type = "OpenstackLogFile"
logger = "%programname%"
pid = "%pid%"
Payload = "%payload%"

[OpenStackTrace.message_fields]
type = "OpenstackLogFile"
logger = "%programname%"
pid = "%pid%"

#[ElseDecoder]
#type = "PayloadRegexDecoder"
#match_regex = '(.*)'

